<script setup lang="ts">
import { ref, onMounted } from 'vue'
import { api } from '../api'
import { useSensorStore } from '../stores/sensors'

interface Report {
  name: string
  path: string
  size_bytes: number
  modified: string
  compressed: boolean
}

const reports = ref<Report[]>([])
const loading = ref(false)
const sensorStore = useSensorStore()

// Tabs
const activeTab = ref<'jobs' | 'export'>('jobs')

// Export Form
const exportForm = ref({
    start_time: '',
    end_time: '',
    sensor_ids: [] as number[],
})
const exportLoading = ref(false)

onMounted(async () => {
  await Promise.all([
    fetchReports(),
    sensorStore.fetchSensors()
  ])
  
  // Set default dates (last 24 hours)
  const now = new Date()
  const yesterday = new Date(now.getTime() - 24 * 60 * 60 * 1000)
  // Format for datetime-local input: YYYY-MM-DDThh:mm
  exportForm.value.end_time = now.toISOString().slice(0, 16)
  exportForm.value.start_time = yesterday.toISOString().slice(0, 16)
})

async function fetchReports() {
  loading.value = true
  try {
    const response = await api.get('/api/config/reports')
    reports.value = response.data
  } catch (e) {
    console.error('Failed to fetch reports:', e)
  } finally {
    loading.value = false
  }
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleString()
}

function downloadReport(report: Report) {
  window.open(`/api/config/reports/${report.name}`, '_blank')
}

async function handleExport() {
    exportLoading.value = true
    try {
        const payload = {
            sensor_ids: exportForm.value.sensor_ids,
            start_time: new Date(exportForm.value.start_time).toISOString(),
            end_time: new Date(exportForm.value.end_time).toISOString(),
            format: 'csv'
        }
        
        const response = await api.post('/api/export/raw', payload, {
            responseType: 'blob' // Important for file download
        })
        
        // Create download link
        const url = window.URL.createObjectURL(new Blob([response.data]))
        const link = document.createElement('a')
        link.href = url
        
        // Extract filename from header or default
        const contentDisposition = response.headers['content-disposition']
        let filename = 'export.csv'
        if (contentDisposition) {
             const filenameMatch = contentDisposition.match(/filename="?([^"]+)"?/)
             if (filenameMatch.length === 2)
                 filename = filenameMatch[1]
        }
        
        link.setAttribute('download', filename)
        document.body.appendChild(link)
        link.click()
        link.remove()
        
    } catch (e: any) {
        alert('Export failed: ' + (e.response?.data?.detail || e.message))
    } finally {
        exportLoading.value = false
    }
}
</script>

<template>
  <div>
    <div class="page-header">
      <h1 class="page-title">Reports & Data</h1>
      <div v-if="activeTab === 'jobs'">
        <button class="btn btn-secondary" @click="fetchReports">
            <i class="pi pi-refresh"></i> Refresh
        </button>
      </div>
    </div>

    <!-- Tabs -->
    <div class="tabs">
        <button 
            :class="['tab-btn', activeTab === 'jobs' ? 'active' : '']"
            @click="activeTab = 'jobs'"
        >
            Generated Reports
        </button>
        <button 
            :class="['tab-btn', activeTab === 'export' ? 'active' : '']"
            @click="activeTab = 'export'"
        >
            Raw Data Export
        </button>
    </div>

    <!-- Job Reports Tab -->
    <div v-if="activeTab === 'jobs'" class="card">
      <div class="card-header">
        <h2 class="card-title">CSV Statistical Reports</h2>
        <span style="font-size: 0.875rem; color: var(--text-muted);">
          Files generated by Statistical Jobs
        </span>
      </div>

      <div v-if="loading" style="text-align: center; padding: 2rem;">
        <i class="pi pi-spin pi-spinner" style="font-size: 2rem;"></i>
      </div>

      <div v-else-if="reports.length === 0" style="text-align: center; padding: 2rem; color: var(--text-muted);">
        <i class="pi pi-file" style="font-size: 3rem; margin-bottom: 1rem;"></i>
        <p>No reports generated yet</p>
      </div>

      <table v-else class="reports-table">
        <thead>
          <tr>
            <th>File Name</th>
            <th>Size</th>
            <th>Generated</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="report in reports" :key="report.name">
            <td>
              <div style="display: flex; align-items: center; gap: 0.5rem;">
                <i :class="['pi', report.compressed ? 'pi-file-zip' : 'pi-file']"></i>
                {{ report.name }}
              </div>
            </td>
            <td>{{ formatSize(report.size_bytes) }}</td>
            <td>{{ formatDate(report.modified) }}</td>
            <td>
              <button class="btn btn-secondary" style="padding: 0.375rem 0.75rem;" @click="downloadReport(report)">
                <i class="pi pi-download"></i>
                Download
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

    <!-- Export Tab -->
    <div v-if="activeTab === 'export'" class="card">
        <div class="card-header">
            <h2 class="card-title">Export Raw Data</h2>
            <span style="font-size: 0.875rem; color: var(--text-muted);">
                Download raw sensor data as CSV (Time-aligned)
            </span>
        </div>
        
        <form @submit.prevent="handleExport" class="export-form">
            <div class="form-row">
                <div class="form-group">
                    <label>Start Time</label>
                    <input type="datetime-local" v-model="exportForm.start_time" class="form-input" required max="2030-12-31T23:59">
                </div>
                <div class="form-group">
                    <label>End Time</label>
                    <input type="datetime-local" v-model="exportForm.end_time" class="form-input" required max="2030-12-31T23:59">
                </div>
            </div>

            <div class="form-group">
                <label>Select Sensors ({{ exportForm.sensor_ids.length }})</label>
                <div class="sensor-select-list">
                    <label v-for="sensor in sensorStore.sensors" :key="sensor.id" class="check-item">
                        <input type="checkbox" :value="sensor.id" v-model="exportForm.sensor_ids">
                        {{ sensor.name }}
                    </label>
                </div>
            </div>

            <div class="form-actions">
                <button type="submit" class="btn btn-primary" :disabled="exportLoading || exportForm.sensor_ids.length === 0">
                    <i v-if="exportLoading" class="pi pi-spin pi-spinner"></i>
                    <i v-else class="pi pi-download"></i>
                    Export CSV
                </button>
            </div>
        </form>
    </div>

  </div>
</template>

<style scoped>
.tabs {
    display: flex;
    gap: 1rem;
    margin-bottom: 1.5rem;
    border-bottom: 1px solid var(--border);
    padding-bottom: 0.5rem;
}

.tab-btn {
    background: none;
    border: none;
    padding: 0.5rem 1rem;
    color: var(--text-muted);
    font-weight: 600;
    cursor: pointer;
    border-bottom: 2px solid transparent;
    transition: all 0.2s;
}

.tab-btn:hover {
    color: var(--text);
}

.tab-btn.active {
    color: var(--primary);
    border-bottom-color: var(--primary);
}

.reports-table {
  width: 100%;
  border-collapse: collapse;
}

.reports-table th,
.reports-table td {
  padding: 0.875rem 1rem;
  text-align: left;
  border-bottom: 1px solid var(--border);
}

.reports-table th {
  font-size: 0.75rem;
  text-transform: uppercase;
  color: var(--text-muted);
  font-weight: 600;
}

.reports-table tr:hover {
  background: var(--surface-hover);
}

/* Form Styles */
.export-form {
    padding: 1.5rem;
    display: flex;
    flex-direction: column;
    gap: 1.5rem;
}
.form-row {
    display: flex;
    gap: 2rem;
}
.form-group {
    display: flex;
    flex-direction: column;
    gap: 0.5rem;
    flex: 1;
}
.form-input {
    padding: 0.75rem;
    background: var(--input-bg);
    border: 1px solid var(--border);
    border-radius: 6px;
    color: var(--text);
}
.sensor-select-list {
    max-height: 200px;
    overflow-y: auto;
    border: 1px solid var(--border);
    border-radius: 6px;
    padding: 0.75rem;
    display: grid;
    grid-template-columns: repeat(auto-fill, minmax(200px, 1fr));
    gap: 0.5rem;
    background: var(--input-bg);
}
.check-item {
    display: flex;
    gap: 0.5rem;
    align-items: center;
    cursor: pointer;
}
.form-actions {
    display: flex;
    justify-content: flex-end;
}
</style>

async function fetchReports() {
  loading.value = true
  try {
    const response = await api.get('/api/config/reports')
    reports.value = response.data
  } catch (e) {
    console.error('Failed to fetch reports:', e)
  } finally {
    loading.value = false
  }
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
}

function formatDate(dateStr: string): string {
  return new Date(dateStr).toLocaleString()
}

function downloadReport(report: Report) {
  window.open(`/api/config/reports/${report.name}`, '_blank')
}
</script>

<template>
  <div>
    <div class="page-header">
      <h1 class="page-title">Reports</h1>
      <button class="btn btn-secondary" @click="fetchReports">
        <i class="pi pi-refresh"></i>
        Refresh
      </button>
    </div>

    <div class="card">
      <div class="card-header">
        <h2 class="card-title">CSV Statistical Reports</h2>
        <span style="font-size: 0.875rem; color: var(--text-muted);">
          Auto-generated every 1/5/60 minutes
        </span>
      </div>

      <div v-if="loading" style="text-align: center; padding: 2rem;">
        <i class="pi pi-spin pi-spinner" style="font-size: 2rem;"></i>
      </div>

      <div v-else-if="reports.length === 0" style="text-align: center; padding: 2rem; color: var(--text-muted);">
        <i class="pi pi-file" style="font-size: 3rem; margin-bottom: 1rem;"></i>
        <p>No reports generated yet</p>
      </div>

      <table v-else class="reports-table">
        <thead>
          <tr>
            <th>File Name</th>
            <th>Size</th>
            <th>Generated</th>
            <th>Actions</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="report in reports" :key="report.name">
            <td>
              <div style="display: flex; align-items: center; gap: 0.5rem;">
                <i :class="['pi', report.compressed ? 'pi-file-zip' : 'pi-file']"></i>
                {{ report.name }}
              </div>
            </td>
            <td>{{ formatSize(report.size_bytes) }}</td>
            <td>{{ formatDate(report.modified) }}</td>
            <td>
              <button class="btn btn-secondary" style="padding: 0.375rem 0.75rem;" @click="downloadReport(report)">
                <i class="pi pi-download"></i>
                Download
              </button>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</template>

<style scoped>
.reports-table {
  width: 100%;
  border-collapse: collapse;
}

.reports-table th,
.reports-table td {
  padding: 0.875rem 1rem;
  text-align: left;
  border-bottom: 1px solid var(--border);
}

.reports-table th {
  font-size: 0.75rem;
  text-transform: uppercase;
  color: var(--text-muted);
  font-weight: 600;
}

.reports-table tr:hover {
  background: var(--surface-hover);
}
</style>
